export default [
  {
    id: "1",
    categoryId: "1",
    name: "Nike Air Max 270",
    type: "Mens",
    brand: "Nike",
    size: "8-9",
    description: "Nike Air Max 270 in a size 8-9 color black",
    color: "black",
    price: 149.99,
    image: "/uploads/Nike01 (1).jpeg",
    cpu: "1.3GHz Apple A6",
    camera: "8mp f.2.4",
    weight: "132 grams",
    display: "4.0 326 pixel density",
    battery: "1480 mAh",
    memory: "16GB",
  },
  {
    id: "2",
    categoryId: "1",
    name: "Nike Air Force 1",
    type: "Kids",
    brand: "Nike",
    description: "Nike Air Force 1 in a size 3-4 color white",
    size: "3-4",
    color: "white",
    price: 74.99,
    image: "/uploads/Nike02 (1).jpeg",
    cpu: "1.4GHz Apple A8",
    camera: "8mp f/2.2",
    weight: "129g",
    display: "4.7 326 pixel density",
    battery: "1810 mAh",
    memory: "32GB",
  },
  {
    id: "3",
    categoryId: "2",
    name: "Adidas Superstar",
    type: "Womens",
    brand: "Adidas",
    description:
      "The adidas Superstar Shoes first stepped onto the basketball hardwood in 1970. It didn't take long for them to make the leap from athletic gear",
    price: 100.0,
    size: "7-8",
    color: "white striped",
    image: "/uploads/Adidas01 (1).jpg",
    cpu: "Quad-core 1.2 GHz Cortex-A53",
    camera: "12 MP, f/2.1",
    weight: "128g",
    display: "5.0 294 pixel density",
    battery: "2300 mAh",
    memory: "8GB",
  },
  {
    id: "4",
    categoryId: "2",
    name: "Adidas Grand Court",
    brand: "Adidas",
    type: "Mens",
    color: "white",
    description: "White Adidas Grand Court shoes.",
    size: "7-8",
    price: 129.99,
    image: "/uploads/Adidas02 (1).jpg",
    cpu: "Quad-core 2.2 GHz Krait 400",
    camera: "20 MP, f/2.4",
    weight: "209 grams",
    display: "6.0 367 pixel density",
    battery: "3400 mAh",
    memory: "32GB",
  },
  {
    id: "5",
    categoryId: "3",
    name: "Puma SpeedCat LS",
    brand: "Puma",
    type: "Womens",
    size: "8-9",
    color: "black",
    description: "The Puma SpeedCat LS Trainers in black",
    price: 220.0,
    image: "/uploads/Puma01 (1).jpg",
    cpu: "Quad-core 1.7 GHz Krait 300",
    camera: "4mp f/2.0",
    weight: "143 grams",
    display: "4.7 469 pixel density",
    battery: "2300 mAh",
    memory: "64GB",
  },
  {
    id: "6",
    categoryId: "3",
    name: "Puma Jay-Z Hybrid",
    brand: "Puma",
    color: "custom",
    type: "Mens",
    size: "9-10",
    description: "The Jay-Z Hybrid Puma collaboration sneakers.",
    price: 90,
    image: "/uploads/Puma02 (1).jpg",
    cpu: "Octa-core (4x2.1 GHz Cortex-A57 & 4x1.5 GHz Cortex-A53)",
    camera: "8mp (3264x2448)",
    weight: "138 grams",
    display: "5.1 577 pixel density",
    battery: "2550 mAh",
    memory: "128GB",
  },
];
